# Name of the quickstart (required)
name: email

# Displayed in the UI (required)
title: Email

# Long-form description of the quickstart (required)
description: |
  You can send email notifications to users with or without New Relic accounts.

  For more information or support, please go to https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#webhook


# Displayed in search results and recommendations. Summarizes a packs functionality.
summary: |
  Send email notifications to users with or without New Relic accounts.


# Support level: New Relic | Verified | Community (required)
level: Verified

# Authors of the quickstart (required)
authors:
  - Matan Moser (New Relic)
  - Ismail Azam (New Relic)

# Keywords for filtering / searching criteria in the UI
keywords:
  - Email
  - notifications
  - AIOps
  - Incident Intelligence
  - Destinations

# Content / Design
logo: email-logo.png
