# Name of the quickstart (required)
name: service-now

# Displayed in the UI (required)
title: ServiceNow

# Long-form description of the quickstart (required)
description: |
  ServiceNow is a software company that develops a cloud computing platform to help companies manage digital workflows for enterprise operations. You can now Integrate New Relic with ServiceNow Incident-Management and automatically create and update incidents.

  For more information or support, please go to https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#servicenow


# Displayed in search results and recommendations. Summarizes a packs functionality.
summary: |
  Integrate New Relic with ServiceNow Incident-Management and automatically create and update incidents.

# Support level: New Relic | Verified | Community (required)
level: Verified

# Authors of the quickstart (required)
authors:
  - Matan Moser (New Relic)
  - Ismail Azam (New Relic)

# Keywords for filtering / searching criteria in the UI
keywords:
  - Servicenow
  - Atlassian
  - notifications
  - AIOps
  - Incident Intelligence
  - Destinations

# Content / Design
logo: servicenow_logo.svg.png
website: https://www.servicenow.com/